### ISSUE TITLE
consider renaming `lib/io.dart` to `lib/webdriver_io.dart`

### ISSUE THREAD

**Issue by devoncarew** [google/webdriver.dart#55]
In the 0.9.0 version of the package, we import:

    import 'package:webdriver/io.dart';

in the new (unpublished) version, we import:

    import 'package:webdriver/io.dart';

I think `webdriver_io.dart` would be a more semantic import.

**Comment by DrMarcII** [comment]
But that name is so redundant...

**Comment by devoncarew** [comment]
It tells me that there are two different flavors of webdriver, and that which libraries in the package are the best entry-points (`webdriver_io.dart` and `webdriver_html.dart`).

**Comment by DrMarcII** [comment]
There are only 3 possible entry points for the package (everything else is nested in src/ so is out as an entry-point), all of which have appropriate applications:

core.dart is intended for frameworks that are agnostic to the whether they run in a browser or in the VM.
io.dart is for use in the vm.
html.dart is for use in a browser.

I could see renaming them (io.dart to vm.dart, html.dart to browser.dart), but I don't think prepending webdriver_ makes anything clearer. The fact that they are at the top-level already should make it clear that these are the intended entry-points, and the fact that none of them are called webdriver.dart should indicate to the user that they have to make a decision (which is why I chose core.dart instead of webdriver.dart).

**Comment by devoncarew** [comment]
I think it would improve the UX very slightly (even with the redundancy), but it's definitely not a critical point. I'll close this out -
